name: Build Firestorm Windows (No Package)

on:
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Build target branch or tag (例: master または Firestorm_7.1.13)'
        required: true
        default: '7.2.0_preview'  # ← ここを master から変更
      enable_libvlc:
        description: "Enable LibVLC support"
        required: true
        default: "true"
      libvlc_sdk_url:
        description: "URL of LibVLC SDK (7z/zip)"
        required: true
        default: "https://download.videolan.org/pub/videolan/vlc/3.0.9.2/win64/vlc-3.0.9.2-win64.7z"

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ebamolter/phoenix-firestorm
          ref: ${{ github.event.inputs.branch_or_tag }}
          submodules: recursive

      - name: Debug: Show root directory structure
        run: |
          echo "=== ROOT DIR ==="
          dir
          echo "=== phoenix-firestorm DIR ==="
          dir phoenix-firestorm
          echo "=== phoenix-firestorm/indra DIR ==="
          dir phoenix-firestorm\indra

      - name: Install dependencies
        run: |
          choco install --no-progress --yes 7zip cmake git nsis yasm
          choco install --no-progress --yes visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --passive --locale en-US"

      - name: Download and extract LibVLC
        if: ${{ github.event.inputs.enable_libvlc == 'true' }}
        run: |
          mkdir _temp
          cd _temp
          curl -L "${{ github.event.inputs.libvlc_sdk_url }}" -o libvlc.7z
          7z x libvlc.7z -o"libvlc_pkg"

      - name: Configure Firestorm
        run: |
          cd phoenix-firestorm
          bash ./indra/scripts/configure_firestorm.sh \
            --platform windows \
            -- -A x64 \
            -DLL_TESTS:BOOL=FALSE \
            -DPACKAGE:BOOL=Off \
            -DMEDIAPLUGIN_LIBVLC:BOOL=ON \
            -DUSE_VLC:BOOL=ON \
            "-DLibVLC_INCLUDE_DIR=${{ github.workspace }}/phoenix-firestorm/_temp/libvlc_pkg/vlc-3.0.9.2/sdk/include" \
            "-DLibVLC_LIBRARY=${{ github.workspace }}/phoenix-firestorm/_temp/libvlc_pkg/vlc-3.0.9.2/sdk/lib/libvlc.lib" \
            "-DLibVLC_CORE_LIBRARY=${{ github.workspace }}/phoenix-firestorm/_temp/libvlc_pkg/vlc-3.0.9.2/sdk/lib/libvlccore.lib"

      - name: Check for .sln
        run: |
          if (Test-Path "build-vc170-64\Firestorm.sln") {
            Write-Output "✅ Firestorm.sln found."
          } else {
            Write-Output "❌ Firestorm.sln NOT found, attempting manual cmake generation..."
            cmake -S . -B build-vc170-64 -G "Visual Studio 17 2022" -A x64
            dir build-vc170-64
          }
        shell: pwsh

      - name: Build Firestorm
        run: |
          cd build-vc170-64
          msbuild Firestorm.sln /p:Configuration=Release /m
