name: Build Firestorm Windows (With LibVLC)

on:
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Build target branch or tag (例: master または Firestorm_7.1.13)'
        required: true
        default: 'master'
      enable_libvlc:
        description: 'Enable LibVLC support'
        required: true
        default: 'true'
      libvlc_sdk_url:
        description: 'URL of LibVLC SDK (7z/zip)'
        required: true
        default: 'https://download.videolan.org/pub/videolan/vlc/3.0.9.2/win64/vlc-3.0.9.2-win64.7z'

jobs:
  build:
    runs-on: windows-2022

    env:
      AUTOBUILD_BUILD_ID: ${{ github.run_id }}
      LIBVLC_PACKAGE_DIR: ${{ runner.temp }}/libvlc_pkg
      LIBVLC_SDK_DIR: ${{ runner.temp }}/libvlc_pkg/pkg/vlc-3.0.9.2
      LIBVLC_INCLUDE_DIR: ${{ runner.temp }}/libvlc_pkg/pkg/vlc-3.0.9.2/sdk/include
      LIBVLC_LIB_DIR: ${{ runner.temp }}/libvlc_pkg/pkg/vlc-3.0.9.2/sdk/lib

    steps:
      - name: Checkout Firestorm
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.event.inputs.branch_or_tag }}

      - name: Install 7zip
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install 7zip -y

      - name: Extract LibVLC SDK
        if: ${{ github.event.inputs.enable_libvlc == 'true' }}
        run: |
          mkdir $env:LIBVLC_PACKAGE_DIR
          Invoke-WebRequest "${{ github.event.inputs.libvlc_sdk_url }}" -OutFile "$env:LIBVLC_PACKAGE_DIR/libvlc.7z"
          7z x "$env:LIBVLC_PACKAGE_DIR/libvlc.7z" -o"$env:LIBVLC_PACKAGE_DIR/pkg"

      - name: Ensure configure_firestorm.sh is LF and UTF-8
        shell: pwsh
        run: |
          $path = "indra/scripts/configure_firestorm.sh"

          if (!(Test-Path $path)) {
            Write-Error "ファイルが存在しません: $path"
          }

          $content = Get-Content $path -Raw
          $content = $content -replace "`r`n", "`n"
          $content = $content -replace "`r", "`n"
          [System.IO.File]::WriteAllText($path, $content, [System.Text.UTF8Encoding]::new($false))

      - name: Configure with/without LibVLC
        shell: pwsh
        run: |
          $cfg = "indra/scripts/configure_firestorm.sh"

          if (!(Test-Path $cfg)) {
            Write-Error "パスが無効です: $cfg"
          }

          if ($env:LIBVLC_INCLUDE_DIR -and $env:LIBVLC_LIB_DIR) {
            autobuild configure -A 64 -c ReleaseFS_open --platform windows -- `
              --config-script="$cfg" `
              --with-libvlc-includes="$env:LIBVLC_INCLUDE_DIR" `
              --with-libvlc-libs="$env:LIBVLC_LIB_DIR" `
              -- -DPACKAGE:BOOL=Off
          } else {
            autobuild configure -A 64 -c ReleaseFS_open --platform windows -- `
              --config-script="$cfg" `
              -- -DPACKAGE:BOOL=Off
          }

      - name: Post Run actions/checkout@v4
        run: echo "Complete"

