name: Build Firestorm Windows

on:
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Branch or tag to build (例: 7.2.0_preview / Firestorm_7.1.13)'
        required: true
        default: '7.2.0_preview'
      do_package:
        description: 'Create installer/package? (容量・時間が増える)'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout phoenix-firestorm
        uses: actions/checkout@v4
        with:
          repository: FirestormViewer/phoenix-firestorm
          ref: ${{ github.event.inputs.branch_or_tag }}
          fetch-depth: 1

      - name: Enable Git long paths
        shell: pwsh
        run: git config --system core.longpaths true

      # fs-build-variables の取得
      - name: Clone fs-build-variables
        shell: pwsh
        run: |
          $srcDir = "$env:USERPROFILE\src"
          New-Item -ItemType Directory -Path $srcDir -Force | Out-Null
          if (-not (Test-Path "$srcDir\fs-build-variables")) {
            git clone https://github.com/FirestormViewer/fs-build-variables.git "$srcDir\fs-build-variables"
          }

      # Windows用とbash用のパス両方をセット
      - name: Set AUTOBUILD_VARIABLES_FILE for cmd/pwsh and bash
        shell: pwsh
        run: |
          $winPath = Join-Path $env:USERPROFILE 'src\fs-build-variables\variables'
          if (!(Test-Path $winPath)) { throw "variables file not found: $winPath" }
          # Windows形式
          "AUTOBUILD_VARIABLES_FILE=$winPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          # bash形式
          $bashPath = '/' + ($winPath -replace '\\','/' -replace ':','')
          "AUTOBUILD_VARIABLES_FILE_BASH=$bashPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup MSVC dev cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Autobuild
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install autobuild
          autobuild --version

      - name: Configure Firestorm
        shell: cmd
        run: |
          echo AUTOBUILD_VARIABLES_FILE=%AUTOBUILD_VARIABLES_FILE%
          echo AUTOBUILD_VARIABLES_FILE_BASH=%AUTOBUILD_VARIABLES_FILE_BASH%
          autobuild configure -A 64 -c ReleaseFS_open

      - name: Build Firestorm
        shell: cmd
        run: |
          autobuild build -A 64 -c ReleaseFS_open --no-configure

      - name: Package Firestorm (optional)
        if: ${{ github.event.inputs.do_package == 'true' }}
        shell: cmd
        run: |
          autobuild package -A 64 -c ReleaseFS_open

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firestorm-windows
          path: |
            build-vc*-64\newview\packaged
            build-vc*-64\newview\ReleaseFS_open
