name: Build Firestorm Windows (No Package)

on:
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Build target branch or tag'
        required: true
        default: '7.2.0_preview'  # ← ここを修正

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_or_tag }}

      - name: Install 7zip and autobuild
        run: |
          choco install 7zip --no-progress -y
          curl -L https://downloads.secondlife.com/hg/autobuild/autobuild-windows.zip -o autobuild.zip
          mkdir C:\autobuild
          tar -xf autobuild.zip -C C:\autobuild
          echo "C:\autobuild" >> $GITHUB_PATH
        shell: pwsh

      - name: Download and Extract LibVLC
        run: |
          mkdir _temp
          curl -L "https://download.videolan.org/pub/videolan/vlc/3.0.9.2/win64/vlc-3.0.9.2-win64.7z" -o _temp/libvlc.7z
          mkdir _temp/libvlc_pkg
          7z x _temp/libvlc.7z -o_temp/libvlc_pkg
        shell: pwsh

      - name: Set Environment Variables
        run: |
          echo "LIBVLC_INCLUDE_DIR=${{ github.workspace }}/_temp/libvlc_pkg/vlc-3.0.9.2/sdk/include" >> $GITHUB_ENV
          echo "LIBVLC_LIB_DIR=${{ github.workspace }}/_temp/libvlc_pkg/vlc-3.0.9.2/sdk/lib" >> $GITHUB_ENV
          echo "LL_BUILD=windows" >> $GITHUB_ENV
          echo "AUTOBUILD_VARIABLES_FILE=${{ github.workspace }}/autobuild.xml" >> $GITHUB_ENV
        shell: bash

      - name: Configure Firestorm
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          set -x
          if [[ -f "./indra/scripts/configure_firestorm.sh" ]]; then
            if [[ -n "$LIBVLC_INCLUDE_DIR" ]]; then
              ./indra/scripts/configure_firestorm.sh --platform windows -- -A x64 \
                -DLL_TESTS:BOOL=FALSE \
                -DPACKAGE:BOOL=Off \
                -DMEDIAPLUGIN_LIBVLC:BOOL=ON \
                -DUSE_VLC:BOOL=ON \
                "-DLibVLC_INCLUDE_DIR=$LIBVLC_INCLUDE_DIR" \
                "-DLibVLC_LIBRARY=$LIBVLC_LIB_DIR/libvlc.lib" \
                "-DLibVLC_CORE_LIBRARY=$LIBVLC_LIB_DIR/libvlccore.lib"
            else
              ./indra/scripts/configure_firestorm.sh --platform windows -- -A x64 \
                -DLL_TESTS:BOOL=FALSE \
                -DPACKAGE:BOOL=Off \
                -DMEDIAPLUGIN_LIBVLC:BOOL=OFF \
                -DUSE_VLC:BOOL=OFF
            fi
          else
            echo "❌ configure_firestorm.sh not found"
            exit 1
          fi

      - name: Check Firestorm.sln
        shell: pwsh
        run: |
          if (Test-Path "build-vc170-64\Firestorm.sln") {
            Write-Output "✅ Firestorm.sln found."
          } else {
            Write-Output "❌ Firestorm.sln NOT found, generating with cmake..."
            cmake -S "${{ github.workspace }}/indra" -B "${{ github.workspace }}/build-vc170-64" -G "Visual Studio 17 2022" -A x64
          }

      - name: Build
        shell: pwsh
        run: |
          msbuild build-vc170-64\Firestorm.sln /p:Configuration=Release /m
