name: Build Firestorm Windows (No Packaging)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Firestorm source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Autobuild
        run: |
          choco install python --version=3.10.9
          choco install sevenzip
          pip install autobuild

      - name: Set AUTOBUILD_VARIABLES_FILE
        run: echo "AUTOBUILD_VARIABLES_FILE=autobuild.xml" >> $env:GITHUB_ENV

      - name: Fetch LibVLC SDK (7z/zip)
        run: |
          $url = "https://download.videolan.org/pub/videolan/vlc/3.0.9.2/win64/vlc-3.0.9.2-win64.7z"
          $zip = "vlc-sdk.7z"
          Invoke-WebRequest -Uri $url -OutFile $zip
          7z x $zip -o"vlc"
          $ibdir = Get-ChildItem -Recurse -Path "vlc" -Directory | Where-Object { $_.Name -eq "sdk" }
          if ($ibdir) {
            echo "LIBVLC_SDK_PATH=$($ibdir.FullName)" >> $env:GITHUB_ENV
          } else {
            echo "LibVLC SDK not found in extracted files."
            exit 1
          }

      - name: Configure (with/without LibVLC)
        run: |
          autobuild configure -c ReleaseFS_open -- --version --platform windows

      - name: Build
        run: |
          autobuild build -c ReleaseFS_open -A 64 --no-configure -- /m

      - name: Upload unpackaged viewer
        uses: actions/upload-artifact@v4
        with:
          name: firestorm-unpackaged
          path: build-vc170-64/newview/Release
