name: Debug Firestorm Script Paths

on:
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Branch or tag to build'
        required: true
        default: 'master'

jobs:
  debug:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_or_tag }}
          submodules: recursive

      - name: Show Current Paths and Files
        shell: pwsh
        run: |
          Write-Host "=== GITHUB_WORKSPACE ==="
          Write-Host $env:GITHUB_WORKSPACE
          Write-Host ""

          Write-Host "=== Current Directory ==="
          Get-Location
          Write-Host ""

          Write-Host "=== All configure_firestorm.sh files under workspace ==="
          Get-ChildItem -Recurse -Path $env:GITHUB_WORKSPACE -Filter "configure_firestorm.sh" | ForEach-Object {
            Write-Host $_.FullName
          }
          Write-Host ""

      - name: Check ../scripts from various working dirs
        shell: pwsh
        run: |
          $dirs = @(
            "$env:GITHUB_WORKSPACE",
            "$env:GITHUB_WORKSPACE/indra",
            "$env:GITHUB_WORKSPACE/indra/build-vc170-64/newview"
          )

          foreach ($d in $dirs) {
            Write-Host "=== Testing from $d ==="
            Push-Location $d
            $target = Join-Path ".." "scripts\configure_firestorm.sh"
            Write-Host "Looking for: $target"
            if (Test-Path $target) {
              Write-Host "FOUND: " (Resolve-Path $target).Path
            } else {
              Write-Host "NOT FOUND"
            }
            Pop-Location
            Write-Host ""
          }

      - name: Finish
        run: echo "Debug finished."
