name: Build Firestorm Windows (No Package)

on:
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Build target branch or tag (例: master または Firestorm_7.1.13)'
        required: true
        default: 'master'
      enable_libvlc:
        description: "Enable LibVLC support"
        required: true
        default: "true"
      libvlc_sdk_url:
        description: "URL of LibVLC SDK (7z/zip)"
        required: true
        default: "https://download.videolan.org/pub/videolan/vlc/3.0.9.2/win64/vlc-3.0.9.2-win64.7z"

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install 7zip
        run: choco install 7zip -y

      - name: Extract LibVLC SDK
        run: |
          mkdir libvlc_pkg
          curl -L ${{ github.event.inputs.libvlc_sdk_url }} -o libvlc.7z
          7z x libvlc.7z -olibvlc_pkg
        shell: pwsh

      - name: Ensure configure_firestorm.sh is LF and UTF-8
        run: |
          $path = "indra/scripts/configure_firestorm.sh"
          (Get-Content $path) | Set-Content -Encoding UTF8 -NoByteOrderMark $path
        shell: pwsh

      - name: Configure with/without LibVLC
        working-directory: indra
        shell: pwsh
        run: |
          $cfg = "./scripts/configure_firestorm.sh"

          if (!(Test-Path $cfg)) {
            Write-Error "パスが無効です: $cfg"
            exit 1
          }

          if ($env:LIBVLC_INCLUDE_DIR -and $env:LIBVLC_LIB_DIR) {
            autobuild configure -A 64 -c ReleaseFS_open --platform windows -- `
              --config-script="$cfg" `
              --with-libvlc-includes="$env:LIBVLC_INCLUDE_DIR" `
              --with-libvlc-libs="$env:LIBVLC_LIB_DIR" `
              -- -DPACKAGE:BOOL=Off
          } else {
            autobuild configure -A 64 -c ReleaseFS_open --platform windows -- `
              --config-script="$cfg" `
              -- -DPACKAGE:BOOL=Off
          }
        env:
          LIBVLC_INCLUDE_DIR: ${{ github.workspace }}\libvlc_pkg\vlc-3.0.9.2\sdk\include
          LIBVLC_LIB_DIR: ${{ github.workspace }}\libvlc_pkg\vlc-3.0.9.2\sdk\lib
