- name: Configure with configure_firestorm.sh
  shell: bash
  run: |
    if [[ "$LIBVLC_DETECTED" != "0" ]]; then
      ./indra/scripts/configure_firestorm.sh -A 64 -c ReleaseFS_open -- \
        -DLL_TESTS:BOOL=FALSE \
        -DPACKAGE:BOOL=Off \
        -DMEDIAPLUGIN_LIBVLC:BOOL=ON \
        -DUSE_VLC:BOOL=ON \
        "-DLibVLC_INCLUDE_DIR=$LIBVLC_INCLUDE_DIR" \
        "-DLibVLC_LIBRARY=$LIBVLC_LIB_DIR/libvlc.lib" \
        "-DLibVLC_CORE_LIBRARY=$LIBVLC_LIB_DIR/libvlccore.lib"
    else
      ./indra/scripts/configure_firestorm.sh -A 64 -c ReleaseFS_open -- \
        -DLL_TESTS:BOOL=FALSE \
        -DPACKAGE:BOOL=Off \
        -DMEDIAPLUGIN_LIBVLC:BOOL=OFF \
        -DUSE_VLC:BOOL=OFF
    fi
