name: Build Firestorm Windows (No Package)

on:
  workflow_dispatch:
    inputs:
      branch_or_tag:
        description: 'Build target branch or tag (例: master または Firestorm_7.1.13)'
        required: true
        default: 'master'
      enable_libvlc:
        description: "Enable LibVLC support"
        required: true
        default: "true"
      libvlc_sdk_url:
        description: "URL of LibVLC SDK (7z/zip)"
        required: true
        default: "https://download.videolan.org/pub/videolan/vlc/3.0.9.2/win64/vlc-3.0.9.2-win64.7z"

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_or_tag }}
          submodules: recursive

      - name: Install Autobuild
        run: |
          choco install -y sevenzip git cmake python3
          pip install autobuild

      - name: Convert variables.txt for Windows
        shell: pwsh
        run: |
          $src = "$env:GITHUB_WORKSPACE\\variables.txt"
          $dst = "$env:RUNNER_TEMP\\variables_win.txt"
          Get-Content $src | ForEach-Object {
            if ($_ -match '^\s*#') { return } # コメント行スキップ
            if ($_ -match '^\s*$') { return } # 空行スキップ
            $_ -replace 'export\s+', '' -replace '"', '' -replace '=', ' ' | Out-File -Append -FilePath $dst
          }
          echo "AUTOBUILD_VARIABLES_FILE=$dst" >> $env:GITHUB_ENV

      - name: Fetch LibVLC SDK (7z/zip)
        if: ${{ github.event.inputs.enable_libvlc == 'true' }}
        shell: pwsh
        run: |
          $url = "${{ github.event.inputs.libvlc_sdk_url }}"
          $dst = "$env:RUNNER_TEMP\libvlc_pkg"
          $zip = "$dst\pkg"
          New-Item -ItemType Directory -Force -Path $dst | Out-Null
          $fname = "$dst\$(Split-Path $url -Leaf)"
          Invoke-WebRequest -Uri $url -OutFile $fname -UseBasicParsing

          if ($fname.ToLower().EndsWith(".7z")) {
            $sevenZip = "C:\Program Files\7-Zip\7z.exe"
            & "$sevenZip" x $fname "-o$zip" -y | Out-Null
          } else {
            Expand-Archive -Path $fname -DestinationPath $zip -Force
          }

          $inc = Get-ChildItem -Recurse -Path $zip -Directory | Where-Object {
            Test-Path (Join-Path $_.FullName "vlc\vlc.h")
          } | Select-Object -First 1

          $libdir = Get-ChildItem -Recurse -Path $zip -Directory | Where-Object {
            (Test-Path (Join-Path $_.FullName "libvlc.lib")) -and (Test-Path (Join-Path $_.FullName "libvlccore.lib"))
          } | Select-Object -First 1

          $dlldir = Get-ChildItem -Recurse -Path $zip -Directory | Where-Object {
            (Get-ChildItem -Path $_.FullName -Filter "libvlc.dll" -ErrorAction SilentlyContinue).Count -gt 0
          } | Select-Object -First 1

          if ($inc -and $libdir) {
            echo "LIBVLC_INCLUDE_DIR=$($inc.FullName)" >> $env:GITHUB_ENV
            echo "LIBVLC_LIB_DIR=$($libdir.FullName)" >> $env:GITHUB_ENV
          } else {
            echo "LIBVLC_DETECTED=0" >> $env:GITHUB_ENV
          }
          if ($dlldir) { echo "PATH=$($dlldir.FullName);$env:PATH" >> $env:GITHUB_ENV }

      - name: Configure (with/without LibVLC)
        run: |
          if ($env:LIBVLC_DETECTED -ne "0") {
            autobuild configure --platform windows -- --with-libvlc-includes="$env:LIBVLC_INCLUDE_DIR" --with-libvlc-libs="$env:LIBVLC_LIB_DIR"
          } else {
            autobuild configure --platform windows
          }

      - name: Build
        run: autobuild build -c ReleaseFS_open -A 64 --no-configure -- /m:1 /v:m "/clp:ErrorsOnly;Summary"

      - name: Upload unpackaged viewer
        uses: actions/upload-artifact@v4
        with:
          name: firestorm-unpackaged
          path: build-vc170-64/newview/Release
