name: Windows FS Build (No Package)

on:
  workflow_dispatch:
    inputs:
      fs_version:
        description: 'Branch or tag to build (例: Firestorm_7.1.13)'
        required: true
        default: 'Firestorm_7.1.13'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Firestorm
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.fs_version }}
          submodules: recursive

      - name: Install Autobuild
        run: |
          pip install autobuild

      - name: Set AUTOBUILD_VARIABLES_FILE
        run: |
          echo "set AUTOBUILD_VARIABLES_FILE=%CD%\\autobuild.xml" >> %GITHUB_ENV%

      - name: Fetch LibVLC SDK (7z)
        run: |
          $url = "https://download.videolan.org/pub/videolan/vlc/3.0.9.2/win64/vlc-3.0.9.2-win64.7z"
          $out = "$env:RUNNER_TEMP\\vlc.7z"
          Invoke-WebRequest -Uri $url -OutFile $out
          mkdir "$env:RUNNER_TEMP\\vlc" | Out-Null
          & "C:\\Program Files\\7-Zip\\7z.exe" x $out -o"$env:RUNNER_TEMP\\vlc" -y
          $sdkPath = Get-ChildItem -Recurse -Path "$env:RUNNER_TEMP\\vlc" -Directory | Where-Object { $_.Name -like "sdk" }
          if (-not $sdkPath) { throw "LibVLC SDK not found" }
          echo "set LIBVLC_SDK_DIR=$($sdkPath.FullName)" >> $env:GITHUB_ENV

      - name: Configure (with LibVLC)
        run: |
          autobuild configure -A 64 --verbose -- -DLL_BUILD=ON -DLIBVLC_SDK_DIR="$env:LIBVLC_SDK_DIR"

      - name: Build
        run: |
          autobuild build -A 64 --verbose

      - name: Upload unpackaged viewer
        uses: actions/upload-artifact@v3
        with:
          name: Firestorm-Unpackaged
          path: build-vc170-64/newview/Release
