name: Build Firestorm Windows

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to build (例: 7.2.0_preview / Firestorm_7.1.13)'
        required: true
        default: '7.2.0_preview'
      create_installer:
        description: 'Create installer/package? (容量・時間が増大します)'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
          submodules: true

      - name: Prepare Variables File
        run: echo "変数ファイル準備中..."

      - name: Fix dependencies for libgoogle-perftools-dev
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libunwind-dev

      - name: Install prerequisites
        shell: bash
        run: |
          sudo apt-get install -y \
            libgoogle-perftools-dev \
            uuid-dev \
            python3-pip

      - name: Configure Firestorm
        run: |
          autobuild configure -A 64 -c ReleaseFS_open --platform windows

      - name: Build Firestorm
        run: autobuild build -A 64 -c ReleaseFS_open --platform windows

      - name: Package (optional)
        if: ${{ github.event.inputs.create_installer == 'true' }}
        run: autobuild package -A 64 -c ReleaseFS_open --platform windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firestorm-windows
          path: build-*/newview/Release
