name: test Build Firestorm Windows

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to build (例: 7.2.0_preview / Firestorm_7.1.13)'
        required: true
        default: '7.2.0_preview'
      create_package:
        description: 'Create installer/package? (容量・時間が増大します)'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Firestorm
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.branch }}
        submodules: recursive

    - name: Install Autobuild
      run: |
        pip install autobuild

    - name: Prepare Variables File
      run: |
        # Linuxビルド時に使ったvariablesファイルをArtifactから取得
        # または手動で同ディレクトリに置く
        echo "AUTOBUILD_VARIABLES_FILE=${{ github.workspace }}\\indra\\build_secrets\\variables" >> $env:GITHUB_ENV

    - name: Configure Firestorm
      run: autobuild configure -A 64 -c ReleaseFS_open -- -platform windows

    - name: Build Firestorm
      run: autobuild build -A 64 -c ReleaseFS_open -- -platform windows

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: firestorm-windows
        path: build-vc*/newview/Release/*

