name: Build Firestorm Windows Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch or tag to build (例: 7.2.0_preview / Firestorm_7.1.13)'
        required: true
        default: '7.2.0_preview'
      create_package:
        description: 'Create installer/package? (容量・時間が増大します)'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Firestorm
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v2

      - name: Install autobuild
        run: |
          python -m pip install autobuild

      - name: Prepare Variables File
        run: |
          echo "AUTOBUILD_VARIABLES_FILE=indra/build_secrets/variables" >> $env:GITHUB_ENV

      - name: Configure Firestorm
        run: |
          autobuild configure -A 64 -c ReleaseFS_open --platform windows

      - name: Build Firestorm
        run: |
          autobuild build -A 64 -c ReleaseFS_open --no-configure --platform windows

      - name: Package (optional)
        if: ${{ github.event.inputs.create_package == 'true' }}
        run: |
          autobuild package -A 64 -c ReleaseFS_open --platform windows

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firestorm-windows
          path: build-vc*/newview/Release/*.exe
