name: Build Firestorm Windows Test

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Firestorm
        uses: actions/checkout@v4

      - name: Install Autobuild
        run: |
          pip install autobuild

      - name: Configure Firestorm Linux
        run: |
          autobuild configure -A 64 -c ReleaseFS_open --platform linux

      - name: Save Variables File
        run: |
          mkdir -p indra/build_secrets
          cp indra/build_secrets/variables variables
        shell: bash

      - name: Upload Variables File
        uses: actions/upload-artifact@v4
        with:
          name: variables
          path: variables

  build-windows:
    needs: build-linux
    runs-on: windows-2022
    steps:
      - name: Checkout Firestorm
        uses: actions/checkout@v4

      - name: Download Variables File
        uses: actions/download-artifact@v4
        with:
          name: variables
          path: .

      - name: Prepare Variables File
        run: |
          New-Item -ItemType Directory -Force -Path "indra/build_secrets" | Out-Null
          Copy-Item "variables" "indra/build_secrets/variables"
        shell: pwsh

      - name: Install Autobuild
        run: |
          pip install autobuild

      - name: Configure Firestorm Windows
        run: |
          autobuild configure -A 64 -c ReleaseFS_open --platform windows

      - name: Build Firestorm
        run: |
          autobuild build -A 64 -c ReleaseFS_open --no-configure --verbose
